name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Instalar dependencias
        run: pip install pytest

      - name: Ejecutar pruebas
        run: python -m unittest test_suma.py
